### ISSUE TITLE
Build Fail - ubuntu 16.04 - 4.10.0-20-generic

### ISSUE THREAD

**Issue by alphaaurigae** [ParrotSec/hexinject#3]
$ make
gcc -o hexinject hexinject.c -lpcap
In file included from hexinject.h:19:0,
                 from hexinject.c:8:
hexstring.h: In function ‘str_to_hex’:
hexstring.h:32:9: warning: implicit declaration of function ‘isdigit’ [-Wimplicit-function-declaration]
      if(isdigit(str[0])) {
         ^~~~~~~
In file included from hexinject.h:20:0,
                 from hexinject.c:8:
hexdump.h: In function ‘hex_dump’:
hexdump.h:40:13: warning: implicit declaration of function ‘isalnum’ [-Wimplicit-function-declaration]
         if (isalnum(c) == 0) {
             ^~~~~~~
In file included from hexinject.h:21:0,
                 from hexinject.c:8:
prettypacket.h: At top level:
prettypacket.h:147:8: warning: return type defaults to ‘int’ [-Wimplicit-int]
 inline field_print (const char *packet_buffer, int field_size, int *counter, const char *field_text) {
        ^~~~~~~~~~~
hexinject.c: In function ‘sniff_hexstr_loop’:
hexinject.c:88:9: warning: implicit declaration of function ‘usleep’ [-Wimplicit-function-declaration]
         usleep(options.sleep_time);
         ^~~~~~
/tmp/user/1000/ccGP04yq.o: In function `tcp_print':
hexinject.c:(.text+0x885): undefined reference to `field_print'
hexinject.c:(.text+0x8a1): undefined reference to `field_print'
hexinject.c:(.text+0x8bd): undefined reference to `field_print'
hexinject.c:(.text+0x8d9): undefined reference to `field_print'
hexinject.c:(.text+0x8f5): undefined reference to `field_print'
/tmp/user/1000/ccGP04yq.o:hexinject.c:(.text+0x911): more undefined references to `field_print' follow
/tmp/user/1000/ccGP04yq.o: In function `ip_print':
hexinject.c:(.text+0xcf2): undefined reference to `protocol_8bit_extract'
hexinject.c:(.text+0xd14): undefined reference to `field_print'
hexinject.c:(.text+0xd30): undefined reference to `field_print'
hexinject.c:(.text+0xd4c): undefined reference to `field_print'
hexinject.c:(.text+0xd68): undefined reference to `field_print'
/tmp/user/1000/ccGP04yq.o: In function `arp_print':
hexinject.c:(.text+0xde6): undefined reference to `field_print'
/tmp/user/1000/ccGP04yq.o:hexinject.c:(.text+0xe02): more undefined references to `field_print' follow
/tmp/user/1000/ccGP04yq.o: In function `ethernet_print':
hexinject.c:(.text+0xf55): undefined reference to `protocol_48bit_extract'
hexinject.c:(.text+0xf75): undefined reference to `field_print'
hexinject.c:(.text+0xf91): undefined reference to `field_print'
hexinject.c:(.text+0xfa2): undefined reference to `protocol_16bit_extract'
hexinject.c:(.text+0xfc4): undefined reference to `field_print'
/tmp/user/1000/ccGP04yq.o: In function `isl_print':
hexinject.c:(.text+0x1074): undefined reference to `field_print'
hexinject.c:(.text+0x1085): undefined reference to `protocol_8bit_extract'
hexinject.c:(.text+0x10ab): undefined reference to `field_print'
hexinject.c:(.text+0x10c7): undefined reference to `field_print'
hexinject.c:(.text+0x10e3): undefined reference to `field_print'
hexinject.c:(.text+0x10ff): undefined reference to `field_print'
hexinject.c:(.text+0x111b): undefined reference to `field_print'
/tmp/user/1000/ccGP04yq.o:hexinject.c:(.text+0x1137): more undefined references to `field_print' follow
/tmp/user/1000/ccGP04yq.o: In function `llc_print':
hexinject.c:(.text+0x1558): undefined reference to `protocol_8bit_extract'
hexinject.c:(.text+0x157a): undefined reference to `field_print'
hexinject.c:(.text+0x158b): undefined reference to `protocol_8bit_extract'
hexinject.c:(.text+0x15ad): undefined reference to `field_print'
hexinject.c:(.text+0x15c9): undefined reference to `field_print'
hexinject.c:(.text+0x1646): undefined reference to `field_print'
hexinject.c:(.text+0x1657): undefined reference to `protocol_16bit_extract'
hexinject.c:(.text+0x1679): undefined reference to `field_print'
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by PalinuroSec** [comment]
hi, we no longer use github, our git repository is https://dev.parrotsec.org

**Comment by PalinuroSec** [comment]
and remember that this package is designed to be compiled on www.parrotsec.org which is based on debian testing, while ubuntu 16.04 has very very old package versions compared to those in the parrot repository

**Comment by alphaaurigae** [comment]
ok, thx for the info :)

**Comment by PalinuroSec** [comment]
have you seen if it compiles on ubuntu 17.04?
